apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: hello-world
  name: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      run: hello-world
  template:
    metadata:
      labels:
        run: hello-world
    spec:
      containers:
      - image: gcr.io/learning-261705/hello-world:latest
        name: hello-world
        ports:
        - containerPort: 5000 
 

